datasources:
  github:
    url: https://api.github.com/search/repositories?q=org:ammarlakis%20topic:featured
  ammarlakis.com:
    url: https://ammarlakis.com/feed.json

inputFiles:
  - README.md.gotmpl

outputFiles:
  - README.md

