name: Update README

on:
  push:
    paths:
      - "README.md.gotmpl"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate README.md with gomplate
        uses: ammarlakis/action-gomplate@v1
        with:
          input_file: README.md.gotmpl

      - name: Commit and Push Changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m "Automated update: Regenerate README.md" || exit 0
          git push origin
